/* -------------------------------------------------
Project:	PAWN
Purpose:	Custom APIs
Author:		hjkim (godmode2k@hotmail.com)
Date:		November 16, 2014
Filename:	customapis.inc

Last modified: November 16, 2014
License: n/a

-------------------------------------------------
Note:
-------------------------------------------------
------------------------------------------------- */



#if defined _customapis_included
  #endinput
#endif
#define _customapis_included
#pragma library CustomAPIs

native myfunc1(var1, var2);
